spring.application.name=PersonalPlatform

spring.datasource.url=jdbc:postgresql://dpg-da9s1qpsrm7s73d680cg-a.oregon-postgres.render.com:5432/db_for_personal_platform
spring.datasource.username=db_for_personal_platform_user
spring.datasource.password=OA77V3kJMvmZKGV0kd1eQAvUTJO6kcBj

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
